services:
  - type: web
    name: amazon-price-tracker-api
    env: node
    rootDirectory: backend
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
      - key: RECEIVER_EMAIL
        sync: false
      - key: SCHEDULE_TIME
        value: "0 9 * * *"
